# Generated by Django 5.2.1 on 2025-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('imgs', models.JSONField(blank=True, verbose_name='Ссылки на фотографии')),
            ],
        ),
    ]
