# Generated by Django 5.2.1 on 2025-06-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options_placeimage_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
